### ISSUE TITLE
Impossible to use getList because missing preference for StockItemResultsInterface

### ISSUE THREAD

**Issue by delyriand** [Smile-SA/magento2-module-retailer-offer-inventory#2]
In di.xml file, missing a preference instruction for `Smile\RetailerOfferInventory\Api\Data\StockItemResultsInterface` class : 
```xml
<preference for="Smile\RetailerOfferInventory\Api\Data\StockItemResultsInterface" type="Magento\Framework\Api\SearchResults" />
```

**Comment by romainruaud** [comment]
Hello @delyriand can you propose a PR quickly for this one ?

Regards

**Comment by delyriand** [comment]
Hi @romainruaud, it is done! (PR #3)
