### ISSUE TITLE
StockItemPlugin fatal error

### ISSUE THREAD

**Issue by loiczam** [Smile-SA/magento2-module-retailer-offer-inventory#7]
Hello,

We have a fatal error with a plugin of the module, at line 64 we have 
`$this->setData(...)`
But this fonction doesn't exist in this class.

The php error backtrace :
`Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Smile\\RetailerOfferInventory\\Plugin\\StockItemPlugin::setData() in /var/www/vendor/smile/module-retailer-offer-inventory/Plugin/StockItemPlugin.php:64\nStack trace:
#0 /var/www/vendor/magento/framework/Interception/Interceptor.php(146): Smile\\RetailerOfferInventory\\Plugin\\StockItemPlugin->afterSetIsInStock(Object(Magento\\CatalogInventory\\Model\\Stock\\Item\\Interceptor), Object(Magento\\CatalogInventory\\Model\\Stock\\Item\\Interceptor), 0)
#1 /var/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\CatalogInventory\\Model\\Stock\\Item\\Interceptor->Magento\\Framework\\Interception\\{closure}(0)
#2 /var/www/generated/code/Magento/CatalogInventory/Model/Stock/Item/Interceptor.php(26): Magento\\CatalogInventory\\Model\\Stock\\Item\\Interceptor->___callPlugins('setIsInStock', Array, Array)`

**Comment by Fdec** [comment]
Hi @loiczam 

I need more information. Can you respect the format of issue ?



### Preconditions



Magento Version :


Module Retailer Offer Inventory Version :


Environment :


Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by Fdec** [comment]
Fixed
